/**
 * Initial Mock Database Seed
 * Extended for 16 Loan Application Records, 8 Users, and 6 Schemes
 */
const MOCK_DB = {
  schemes: [
    {
      loan_type: "personal_loan",
      display_name: "Personal Loan",
      description: "Quick, collateral-free funding for medical emergencies, travel, weddings, or debt consolidation.",
      min_amount: 50000,
      max_amount: 2500000,
      interest_rate_min: 10.49,
      interest_rate_max: 18.0,
      min_tenure_months: 12,
      max_tenure_months: 60,
      min_age: 21,
      max_age: 60,
      min_income_annual: 300000,
      min_credit_score: 650,
      max_foir: 50.0,
      document_checklist: {
        kyc_documents: ["PAN Card", "Aadhaar Card", "Proof of address"],
        income_documents: ["Last 3 months salary slips", "Form 16 / ITR for 2 years"],
        bank_documents: ["6 months bank statement"],
        loan_specific_documents: ["Declaration of purpose"],
        collateral_documents: []
      },
      source_url: "https://rbi.org.in/Scripts/BS_ViewMasCirculardetails.aspx?id=9862",
      last_verified: "2026-08-01"
    },
    {
      loan_type: "home_loan",
      display_name: "Home Loan",
      description: "Long-term financing for purchasing new residential property, plot construction, or home renovation.",
      min_amount: 500000,
      max_amount: 15000000,
      interest_rate_min: 8.50,
      interest_rate_max: 10.25,
      min_tenure_months: 60,
      max_tenure_months: 360,
      min_age: 23,
      max_age: 65,
      min_income_annual: 500000,
      min_credit_score: 700,
      max_foir: 60.0,
      document_checklist: {
        kyc_documents: ["PAN Card", "Aadhaar Card", "Passport photo"],
        income_documents: ["Salary Slips (3 mos)", "Form 16", "ITR (2 yrs)"],
        bank_documents: ["12 months bank statement"],
        loan_specific_documents: ["Sale Deed", "Approved Building Plan", "NOC from builder"],
        collateral_documents: ["Property Valuation Report", "Title Search Report"]
      },
      source_url: "https://rbi.org.in/Scripts/NotificationUser.aspx?Id=12128",
      last_verified: "2026-08-01"
    },
    {
      loan_type: "vehicle_loan",
      display_name: "Vehicle / Auto Loan",
      description: "Hassle-free financing for new or pre-owned cars and two-wheelers with up to 90% on-road funding.",
      min_amount: 100000,
      max_amount: 5000000,
      interest_rate_min: 8.90,
      interest_rate_max: 12.5,
      min_tenure_months: 12,
      max_tenure_months: 84,
      min_age: 21,
      max_age: 65,
      min_income_annual: 350000,
      min_credit_score: 680,
      max_foir: 55.0,
      document_checklist: {
        kyc_documents: ["PAN Card", "Aadhaar Card", "Driving License"],
        income_documents: ["Last 3 months salary slip / ITR"],
        bank_documents: ["6 months bank statement"],
        loan_specific_documents: ["Proforma Invoice from Dealer", "Vehicle Valuation (if used)"],
        collateral_documents: ["Hypothecation Deed"]
      },
      source_url: "https://rbi.org.in/Scripts/BS_ViewMasCirculardetails.aspx",
      last_verified: "2026-08-01"
    },
    {
      loan_type: "education_loan",
      display_name: "Education Loan",
      description: "Cover tuition fees, living expenses, and travel for higher studies in premier Indian or international universities.",
      min_amount: 200000,
      max_amount: 7500000,
      interest_rate_min: 9.15,
      interest_rate_max: 11.75,
      min_tenure_months: 36,
      max_tenure_months: 180,
      min_age: 18,
      max_age: 35,
      min_income_annual: 0,
      min_credit_score: 650,
      max_foir: 50.0,
      document_checklist: {
        kyc_documents: ["Student & Co-Applicant PAN & Aadhaar"],
        income_documents: ["Co-applicant ITR / Salary Slips"],
        bank_documents: ["6 months Co-applicant bank statement"],
        loan_specific_documents: ["Admission Offer Letter", "Fee Structure Breakdown", "Marksheets (10th/12th/Graduation)"],
        collateral_documents: ["Collateral Deed (for loans > ₹7.5 Lakhs)"]
      },
      source_url: "https://www.vidyalakshmi.co.in/",
      last_verified: "2026-08-01"
    },
    {
      loan_type: "business_loan",
      display_name: "Business / MSME Loan",
      description: "Working capital, equipment purchase, or business expansion loans for GST-registered sole proprietorships & firms.",
      min_amount: 300000,
      max_amount: 10000000,
      interest_rate_min: 11.5,
      interest_rate_max: 16.5,
      min_tenure_months: 12,
      max_tenure_months: 60,
      min_age: 25,
      max_age: 65,
      min_income_annual: 1000000,
      min_credit_score: 700,
      max_foir: 50.0,
      document_checklist: {
        kyc_documents: ["Promoter PAN & Aadhaar", "Business Registration Proof"],
        income_documents: ["Audited Financials (2 yrs)", "ITR with Computation", "GST Returns (12 mos)"],
        bank_documents: ["12 months Current Account Statement"],
        loan_specific_documents: ["Business Profile", "Ownership Proof of Business Premises"],
        collateral_documents: []
      },
      source_url: "https://rbi.org.in/Scripts/BS_ViewMasCirculardetails.aspx?id=12000",
      last_verified: "2026-08-01"
    },
    {
      loan_type: "gold_loan",
      display_name: "Gold Loan",
      description: "Instant liquidity backed by 18-24K gold ornaments with minimal paperwork and flexible monthly interest payments.",
      min_amount: 25000,
      max_amount: 5000000,
      interest_rate_min: 7.90,
      interest_rate_max: 12.0,
      min_tenure_months: 3,
      max_tenure_months: 36,
      min_age: 18,
      max_age: 75,
      min_income_annual: 0,
      min_credit_score: 300,
      max_foir: 75.0,
      document_checklist: {
        kyc_documents: ["PAN Card", "Aadhaar Card"],
        income_documents: [],
        bank_documents: ["Cancelled Cheque / Bank passbook for disbursement"],
        loan_specific_documents: ["Gold Appraisal Certificate"],
        collateral_documents: ["Gold Jewellery Pledge Agreement"]
      },
      source_url: "https://rbi.org.in/Scripts/BS_ViewMasCirculardetails.aspx?id=9871",
      last_verified: "2026-08-01"
    }
  ],

  users: [
    {
      id: 1,
      full_name: "Ravi Kumar",
      email: "ravi@example.com",
      phone: "9876543210",
      password: "MyPass@123",
      is_admin: false,
      created_at: "2026-08-13T10:00:00"
    },
    {
      id: 2,
      full_name: "Priya Sharma",
      email: "priya@example.com",
      phone: "9123456789",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-12T14:20:00"
    },
    {
      id: 3,
      full_name: "Anand Verma",
      email: "anand.verma@techcorp.in",
      phone: "9811223344",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-10T11:15:00"
    },
    {
      id: 4,
      full_name: "Meera Nair",
      email: "meera.nair@globaled.org",
      phone: "9744556677",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-09T09:40:00"
    },
    {
      id: 5,
      full_name: "Vikram Malhotra",
      email: "vikram@malhotraenterprises.com",
      phone: "9988776655",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-05T16:30:00"
    },
    {
      id: 6,
      full_name: "Sunita Deshmukh",
      email: "sunita.d@fintech.co.in",
      phone: "9822334455",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-03T11:00:00"
    },
    {
      id: 7,
      full_name: "Rajesh Gupta",
      email: "rajesh.gupta@autoworks.com",
      phone: "9711002233",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-02T15:20:00"
    },
    {
      id: 8,
      full_name: "Kavita Patel",
      email: "kavita.patel@solarsolutions.in",
      phone: "9655443322",
      password: "User@123",
      is_admin: false,
      created_at: "2026-08-01T14:10:00"
    },
    {
      id: 99,
      full_name: "System Admin",
      email: "admin@loanapp.com",
      phone: "9999999999",
      password: "Admin@123",
      is_admin: true,
      created_at: "2026-08-01T00:00:00"
    }
  ],

  loans: [
    {
      id: 101,
      user_id: 1,
      applicant_name: "Ravi Kumar",
      applicant_email: "ravi@example.com",
      product_type: "home_loan",
      requested_amount: 4500000,
      sanctioned_amount: 4200000,
      interest_rate_offered: 8.75,
      tenure_months: 240,
      annual_income: 1400000,
      credit_score: 790,
      employment_type: "salaried",
      purpose: "Purchase 3BHK Apartment in Pune",
      property_location: "Baner, Pune",
      foir_ratio: 42.5,
      status: "approved",
      admin_note: "Sanctioned at prime rate of 8.75% based on 790 CIBIL score.",
      applied_at: "2026-08-13T12:30:00",
      reviewed_at: "2026-08-13T16:00:00"
    },
    {
      id: 102,
      user_id: 2,
      applicant_name: "Priya Sharma",
      applicant_email: "priya@example.com",
      product_type: "vehicle_loan",
      requested_amount: 850000,
      sanctioned_amount: 850000,
      interest_rate_offered: 9.15,
      tenure_months: 60,
      annual_income: 950000,
      credit_score: 745,
      employment_type: "salaried",
      purpose: "Purchase electric SUV",
      vehicle_type: "new",
      vehicle_make_model: "Tata Nexon EV Max",
      foir_ratio: 38.0,
      status: "approved",
      admin_note: "Full sanction granted. Vehicle hypothecated deed verified.",
      applied_at: "2026-08-12T15:00:00",
      reviewed_at: "2026-08-13T09:15:00"
    },
    {
      id: 103,
      user_id: 3,
      applicant_name: "Anand Verma",
      applicant_email: "anand.verma@techcorp.in",
      product_type: "personal_loan",
      requested_amount: 300000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 36,
      annual_income: 720000,
      credit_score: 680,
      employment_type: "salaried",
      purpose: "Home renovation & interior design",
      foir_ratio: 48.0,
      status: "pending",
      admin_note: null,
      applied_at: "2026-08-11T10:15:00",
      reviewed_at: null
    },
    {
      id: 104,
      user_id: 5,
      applicant_name: "Vikram Malhotra",
      applicant_email: "vikram@malhotraenterprises.com",
      product_type: "business_loan",
      requested_amount: 2500000,
      sanctioned_amount: 2500000,
      interest_rate_offered: 11.90,
      tenure_months: 48,
      annual_income: 3800000,
      credit_score: 760,
      employment_type: "self_employed",
      purpose: "Machinery procurement & warehouse expansion",
      business_name: "Malhotra Enterprises Pvt Ltd",
      foir_ratio: 35.0,
      status: "approved",
      admin_note: "GST returns and 2-year audited financials verified cleanly.",
      applied_at: "2026-08-08T14:20:00",
      reviewed_at: "2026-08-09T11:30:00"
    },
    {
      id: 105,
      user_id: 4,
      applicant_name: "Meera Nair",
      applicant_email: "meera.nair@globaled.org",
      product_type: "education_loan",
      requested_amount: 1800000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 84,
      annual_income: 600000,
      credit_score: 720,
      employment_type: "salaried",
      purpose: "Higher studies MS CS in Carnegie Mellon University",
      university_name: "Carnegie Mellon University, USA",
      foir_ratio: 41.0,
      status: "pending",
      admin_note: null,
      applied_at: "2026-08-07T11:00:00",
      reviewed_at: null
    },
    {
      id: 106,
      user_id: 1,
      applicant_name: "Ravi Kumar",
      applicant_email: "ravi@example.com",
      product_type: "gold_loan",
      requested_amount: 400000,
      sanctioned_amount: 400000,
      interest_rate_offered: 8.25,
      tenure_months: 12,
      annual_income: 1400000,
      credit_score: 640,
      employment_type: "salaried",
      purpose: "Short-term working capital",
      gold_weight_grams: 85.5,
      gold_purity_karats: 22,
      foir_ratio: 28.0,
      status: "approved",
      admin_note: "Gold appraisal verified 85.5g 22K hallmarked ornaments.",
      applied_at: "2026-08-06T16:45:00",
      reviewed_at: "2026-08-07T10:00:00"
    },
    {
      id: 107,
      user_id: 3,
      applicant_name: "Anand Verma",
      applicant_email: "anand.verma@techcorp.in",
      product_type: "personal_loan",
      requested_amount: 150000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 18,
      annual_income: 720000,
      credit_score: 590,
      employment_type: "salaried",
      purpose: "Debt consolidation",
      foir_ratio: 58.0,
      status: "rejected",
      admin_note: "Rejected due to FOIR exceeding 50% limit and low CIBIL rating.",
      applied_at: "2026-08-04T09:30:00",
      reviewed_at: "2026-08-05T14:15:00"
    },
    {
      id: 108,
      user_id: 6,
      applicant_name: "Sunita Deshmukh",
      applicant_email: "sunita.d@fintech.co.in",
      product_type: "home_loan",
      requested_amount: 7500000,
      sanctioned_amount: 7000000,
      interest_rate_offered: 8.50,
      tenure_months: 300,
      annual_income: 2200000,
      credit_score: 810,
      employment_type: "salaried",
      purpose: "Luxury Villa in Whitefield Bengaluru",
      property_location: "Whitefield, Bengaluru",
      foir_ratio: 32.0,
      status: "approved",
      admin_note: "Approved at prime rate 8.50% based on 810 CIBIL rating.",
      applied_at: "2026-08-03T11:20:00",
      reviewed_at: "2026-08-04T10:00:00"
    },
    {
      id: 109,
      user_id: 7,
      applicant_name: "Rajesh Gupta",
      applicant_email: "rajesh.gupta@autoworks.com",
      product_type: "vehicle_loan",
      requested_amount: 1200000,
      sanctioned_amount: 1200000,
      interest_rate_offered: 9.40,
      tenure_months: 84,
      annual_income: 1100000,
      credit_score: 730,
      employment_type: "self_employed",
      purpose: "Hyundai Creta SX Petrol",
      vehicle_make_model: "Hyundai Creta SX",
      foir_ratio: 41.5,
      status: "approved",
      admin_note: "Vehicle loan sanctioned with 7-year tenure.",
      applied_at: "2026-08-02T15:30:00",
      reviewed_at: "2026-08-03T09:45:00"
    },
    {
      id: 110,
      user_id: 8,
      applicant_name: "Kavita Patel",
      applicant_email: "kavita.patel@solarsolutions.in",
      product_type: "business_loan",
      requested_amount: 4000000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 60,
      annual_income: 4500000,
      credit_score: 765,
      employment_type: "self_employed",
      purpose: "Solar Inverter Assembly Line Expansion",
      business_name: "Solar Solutions India Ltd",
      foir_ratio: 36.0,
      status: "pending",
      admin_note: null,
      applied_at: "2026-08-01T14:30:00",
      reviewed_at: null
    },
    {
      id: 111,
      user_id: 2,
      applicant_name: "Priya Sharma",
      applicant_email: "priya@example.com",
      product_type: "education_loan",
      requested_amount: 2200000,
      sanctioned_amount: 2200000,
      interest_rate_offered: 9.50,
      tenure_months: 120,
      annual_income: 950000,
      credit_score: 745,
      employment_type: "salaried",
      purpose: "MBA at Imperial College London",
      university_name: "Imperial College London, UK",
      foir_ratio: 39.0,
      status: "approved",
      admin_note: "Education loan approved with co-applicant guarantee.",
      applied_at: "2026-07-28T10:00:00",
      reviewed_at: "2026-07-29T16:00:00"
    },
    {
      id: 112,
      user_id: 6,
      applicant_name: "Sunita Deshmukh",
      applicant_email: "sunita.d@fintech.co.in",
      product_type: "gold_loan",
      requested_amount: 250000,
      sanctioned_amount: 250000,
      interest_rate_offered: 8.10,
      tenure_months: 24,
      annual_income: 2200000,
      credit_score: 810,
      employment_type: "salaried",
      purpose: "Emergency liquidity",
      gold_weight_grams: 50.0,
      gold_purity_karats: 24,
      foir_ratio: 18.0,
      status: "approved",
      admin_note: "50g 24K gold coins pledged & appraised.",
      applied_at: "2026-07-25T11:45:00",
      reviewed_at: "2026-07-25T14:20:00"
    },
    {
      id: 113,
      user_id: 7,
      applicant_name: "Rajesh Gupta",
      applicant_email: "rajesh.gupta@autoworks.com",
      product_type: "personal_loan",
      requested_amount: 500000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 48,
      annual_income: 1100000,
      credit_score: 730,
      employment_type: "self_employed",
      purpose: "Wedding expenses",
      foir_ratio: 44.0,
      status: "pending",
      admin_note: null,
      applied_at: "2026-07-22T09:15:00",
      reviewed_at: null
    },
    {
      id: 114,
      user_id: 4,
      applicant_name: "Meera Nair",
      applicant_email: "meera.nair@globaled.org",
      product_type: "vehicle_loan",
      requested_amount: 450000,
      sanctioned_amount: 450000,
      interest_rate_offered: 9.20,
      tenure_months: 36,
      annual_income: 600000,
      credit_score: 720,
      employment_type: "salaried",
      purpose: "Ather 450X Electric Scooter",
      vehicle_make_model: "Ather 450X EV",
      foir_ratio: 29.0,
      status: "approved",
      admin_note: "Approved and disbursed to Ather dealership.",
      applied_at: "2026-07-18T16:00:00",
      reviewed_at: "2026-07-19T11:00:00"
    },
    {
      id: 115,
      user_id: 3,
      applicant_name: "Anand Verma",
      applicant_email: "anand.verma@techcorp.in",
      product_type: "business_loan",
      requested_amount: 1500000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 36,
      annual_income: 720000,
      credit_score: 590,
      employment_type: "salaried",
      purpose: "Retail franchise expansion",
      foir_ratio: 62.0,
      status: "rejected",
      admin_note: "Ineligible business profile & low CIBIL score.",
      applied_at: "2026-07-15T10:30:00",
      reviewed_at: "2026-07-16T15:00:00"
    },
    {
      id: 116,
      user_id: 2,
      applicant_name: "Priya Sharma",
      applicant_email: "priya@example.com",
      product_type: "home_loan",
      requested_amount: 3200000,
      sanctioned_amount: null,
      interest_rate_offered: null,
      tenure_months: 180,
      annual_income: 950000,
      credit_score: 745,
      employment_type: "salaried",
      purpose: "Plot construction in Gurgaon",
      property_location: "Sector 57, Gurgaon",
      foir_ratio: 47.0,
      status: "pending",
      admin_note: null,
      applied_at: "2026-07-10T12:00:00",
      reviewed_at: null
    }
  ],

  documents: [
    {
      id: 101,
      doc_id: 101,
      loan_id: 101,
      doc_category: "kyc",
      doc_type: "pan_card",
      file_name: "Ravi_PAN_Card.pdf",
      file_size: "1.2 MB",
      status: "verified",
      verification_note: "PAN matched with Income Tax Database",
      uploaded_at: "2026-08-13T12:35:00"
    },
    {
      id: 102,
      doc_id: 102,
      loan_id: 101,
      doc_category: "income",
      doc_type: "salary_slip",
      file_name: "Salary_Slips_3Months.pdf",
      file_size: "3.4 MB",
      status: "verified",
      verification_note: "HR verification completed",
      uploaded_at: "2026-08-13T12:36:00"
    },
    {
      id: 103,
      doc_id: 103,
      loan_id: 102,
      doc_category: "loan_specific",
      doc_type: "proforma_invoice",
      file_name: "NexonEV_Proforma_Invoice.pdf",
      file_size: "2.1 MB",
      status: "verified",
      verification_note: "Dealer invoice verified with Tata Motors",
      uploaded_at: "2026-08-12T15:10:00"
    },
    {
      id: 104,
      doc_id: 104,
      loan_id: 104,
      doc_category: "income",
      doc_type: "audited_financials",
      file_name: "Audited_Financials_2Yr.pdf",
      file_size: "5.8 MB",
      status: "verified",
      verification_note: "CA Stamp & Balance Sheet verified",
      uploaded_at: "2026-08-08T14:30:00"
    }
  ],

  init() {
    this.save();
  },

  save() {
    localStorage.setItem('loan_app_mock_db', JSON.stringify({
      users: this.users,
      loans: this.loans,
      documents: this.documents
    }));
  }
};
